---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Download lxc cache
  get_url:
    url: "{{ rpc_repo_url }}/container_images/rpc-trusty-container.old.tgz"
    dest: "/var/cache/lxc/rpc-trusty-container.tgz"
    mode: "0440"
  register: cache_download
  async: 600
  poll: 15
  retries: 10
  delay: 120
  until: cache_download|success

- name: Move lxc cached image into place
  unarchive:
    src: "/var/cache/lxc/rpc-trusty-container.tgz"
    dest: "/var/cache/lxc/"
    copy: "no"
  when: cache_download|changed
